---
title: "novo_all_data_analysis"
output: html_document
date: "2026-01-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
probs_csv <- "/Volumes/T7 Shield/novo_cleavage_site_predictions/novo_alldata_l18_no_TMRs_highprob_logreg_crf_svm_probs.csv"

probs_df <- readr::read_csv(probs_csv, show_col_types = FALSE) %>%
  transmute(
    Entry            = as.character(Entry),
    position         = as.integer(residue_number),
    residue          = as.character(residue),
    prob_logreg      = as.numeric(prob_logreg),
    prob_crf         = as.numeric(prob_crf),
    prob_svm         = as.numeric(prob_svm),
    prob_mean        = as.numeric(prob_mean),
    prob_logreg_norm = as.numeric(prob_logreg_norm),
    prob_crf_norm    = as.numeric(prob_crf_norm),
    prob_svm_norm    = as.numeric(prob_svm_norm),
    prob_mean_norm   = as.numeric(prob_mean_norm)
  ) %>%
  arrange(Entry, position)

length(unique(probs_df$Entry))

```
```{r}
signalp_df <- readr::read_csv(
  "../../data/novo_277_signalP_scores.csv",
  show_col_types = FALSE
) %>%
  dplyr::mutate(
    Entry = as.character(Entry),
    signal_prob = as.numeric(signal_prob)
  )

canon_strg_id <- function(x) {
  x <- stringr::str_trim(x)

  # unify separators
  x <- stringr::str_replace_all(x, ":", "_")

  # turn "-chr" or "+chr" into "_chr" (so strand sign doesn't affect matching)
  x <- stringr::str_replace_all(x, "[-+]chr", "_chr")

  # parse STRG + chr + coords + F/P (M is just literal)
  m <- stringr::str_match(
    x,
    "^(STRG\\.[0-9]+\\.[0-9]+).*?_chr([^_]+)_([0-9]+)-([0-9]+).*?_F_([0-9]+)_P_([0-9]+)_M$"
  )

  out <- ifelse(
    is.na(m[,1]),
    NA_character_,
    paste0(m[,2], "_chr", m[,3], "_", m[,4], "-", m[,5], "_F_", m[,6], "_P_", m[,7], "_M")
  )
  out
}

probs_df <- probs_df %>% mutate(Entry_key = canon_strg_id(Entry))
signalp_df <- signalp_df %>% mutate(Entry_key = canon_strg_id(Entry))

probs_df <- probs_df %>%
  left_join(
    signalp_df %>% dplyr::select(Entry_key, signal_prob),
    by = "Entry_key"
  )

# quick sanity check
dplyr::n_distinct(signalp_df$Entry)
```

# this is the wrong plot (cleavage sit prob vs. signal P)
```{r}

probs_df %>%
  ggplot(aes(x = prob_logreg, y = signal_prob)) +
  geom_point(alpha = 0.3)
```
I now want general model probability against signal P. 
```{r}
```




```{r}
probs_df %>%
  filter(signal_prob > 0.1) %>%
  summarise(n_entries = n_distinct(Entry))
  
```
Making fasta file:

```{r}
library(dplyr)
library(stringr)

fasta_df <- probs_df %>%
  filter(signal_prob > 0.1) %>%
  arrange(Entry, position) %>%
  group_by(Entry) %>%
  summarise(
    sequence = str_c(residue, collapse = ""),
    .groups = "drop"
  )
```

```{r}
library(Biostrings)

aa_set <- AAStringSet(fasta_df$sequence)
names(aa_set) <- fasta_df$Entry

writeXStringSet(
  aa_set,
  filepath = "../../data/novoall_high_prob_high_sinalP.fasta",
  format = "fasta"
)
```

#====================================================================================================
Getting high signal P score fastas for later blasting (BLASTP)

```{r}
signalp_df <- readr::read_csv(
  "../../data/novo_signalP_scores_50_60.csv",
  show_col_types = FALSE
) %>%
  dplyr::mutate(
    Entry = as.character(Entry),
    signal_prob = as.numeric(signal_prob)
  )

canon_strg_id <- function(x) {
  x <- stringr::str_trim(x)

  # unify separators
  x <- stringr::str_replace_all(x, ":", "_")

  # turn "-chr" or "+chr" into "_chr" (so strand sign doesn't affect matching)
  x <- stringr::str_replace_all(x, "[-+]chr", "_chr")

  # parse STRG + chr + coords + F/P (M is just literal)
  m <- stringr::str_match(
    x,
    "^(STRG\\.[0-9]+\\.[0-9]+).*?_chr([^_]+)_([0-9]+)-([0-9]+).*?_F_([0-9]+)_P_([0-9]+)_M$"
  )

  out <- ifelse(
    is.na(m[,1]),
    NA_character_,
    paste0(m[,2], "_chr", m[,3], "_", m[,4], "-", m[,5], "_F_", m[,6], "_P_", m[,7], "_M")
  )
  out
}


# quick sanity check
dplyr::n_distinct(signalp_df$Entry)
```

Now we need to filter for signalP values >0.1

```{r}
signalp_df <- signalp_df %>%
  filter(signal_prob > 0.1)

# quick sanity check
dplyr::n_distinct(signalp_df$Entry)
```

Now we need to save the remaining entries as a fasta to then run in through blast (see python script)


```{r}
library(Biostrings)
library(dplyr)

input_fasta  <- "../../data/novo_alldata_l18_no_TMRs_50_to_60.fasta"
output_fasta <- "../../data/novoall_50_60_high_signalP.fasta"

# helper: normalize Entry IDs so FASTA and signalp_df matchs

normalize_entry <- function(x) {
  x %>%
    gsub("+chr", "_chr", ., fixed = TRUE) %>%
    gsub("-chr", "_chr", ., fixed = TRUE) %>%
    gsub(":", "_", ., fixed = TRUE)
}

# read FASTA

aa <- readAAStringSet(input_fasta)

# normalize FASTA headers

fasta_ids_norm <- normalize_entry(names(aa))

# normalize SignalP entries

signalp_ids_norm <- signalp_df %>%
pull(Entry) %>%
as.character() %>%
normalize_entry()

# subset FASTA

aa_reduced <- aa[fasta_ids_norm %in% signalp_ids_norm]

# write reduced FASTA

writeXStringSet(aa_reduced, output_fasta)

# sanity checks

length(aa_reduced)
```











